----------------南京局数据
--批量导入部门(江苏局部门数据)
------------------------------------------------------------
INSERT INTO T_PUB_DEPT (
	F_DEPT_ID,
	F_DEPT_CODE,
	F_DEPT_NAME,
	F_DEPT_PARENT_ID,
	F_DEPT_TYPE,
	F_SORT_INDEX,
	F_CRT_TIME,
	F_CRT_USER,
	F_DATA_UPD_TIME,
	F_DATA_UPD_USER,
	F_ADDRESS,
	F_ZIP_CODE,
	F_DATA_VALID_FLAG
) SELECT
	T_ORG.ORG_ID AS F_DEPT_ID,
	T_ORG.ORG_CODE AS F_DEPT_CODE,
	T_ORG.ORG_NAME AS F_DEPT_NAME,
	T_ORG.PORG_ID AS F_DEPT_PARENT_ID,
	T_ORG.ORG_TYPE AS F_DEPT_TYPE,
	T_ORG.SORT_INDEX AS F_SORT_INDEX,
	T_ORG.CRT_TIME AS F_CRT_TIME,
	T_ORG.CRT_USER AS F_CRT_USER,
	T_ORG.DATA_UPD_TIME AS F_DATA_UPD_TIME,
	T_ORG.DATA_UPD_USER AS F_DATA_UPD_USER,
	T_ORG.DATA_VALID_FLAG AS F_DATA_VALID_FLAG,
	T_ORG.ADDRESS AS F_ADDRESS,
	T_ORG.ZIPCODE AS F_ZIP_CODE
FROM
	ZJPORTAL.T_ORG@sso T_ORG;

================================================================================================
--批量导入人员
------------------------------------------------------------
INSERT INTO T_PUB_USER (
	F_USER_ID,
	F_LOGIN_NAME,
	F_LOGIN_PWD,
	F_FIRST_NAME,
	F_MIDDLE_NAME,
	F_DISPLAY_NAME,
	F_SEX,
	F_EMAIL,
	F_ID_CARD_NO,
	F_TELEPHONE,
	F_TELEPHONE_SHORT,
	F_MOBILE_NO,
	F_MOBILE_NO_SHORT,
	F_CRT_TIME,
	F_CRT_USER,
	F_DEPT_ID,
	F_IS_NEW_USER,
	F_DATA_UPD_TIME,
	F_DATA_UPD_USER,
	F_DATA_VALID_FLAG,
	F_LOGIN_STATUS,
	F_LOGOUT_TYPE,
	F_DEPT_CODE,
	F_POSITION_CODE,
	F_CURRENT_ORGID,
	F_ADMIN_FLAG,
	F_STAFF_NO,
	F_NATION,
	F_NATIVE_PLACE,
	F_APPARAT,
	F_BIRTHDAY,
	F_EDUCATION,
	F_FINISH_TIME,
	F_FINISH_SCHOOL,
	F_SPECIALTY,
	F_USER_TYPE
) SELECT
	T_USER.USER_ID AS F_USER_ID,
	SUBSTR (
		T_USER.LOGIN_NAME,
		0,
		(
			INSTR (
				T_USER.LOGIN_NAME,
				'@jsciq',
				1,
				1
			) - 1
		)
	) AS F_LOGIN_NAME,
	USERINFO.LOGIN_PWD AS F_LOGIN_PWD,
	T_USER.FIRST_NAME AS F_FIRST_NAME,
	T_USER.MIDDLE_NAME AS F_MIDDLE_NAME,
	T_USER.DISPLAY_NAME AS F_DISPLAY_NAME,
	TRIM (T_USER.SEX) AS F_SEX,
	T_USER.EMAIL AS F_EMAIL,
	T_USER.ID_CARD_NO AS F_ID_CARD_NO,
	T_USER.TELEPHONE AS F_TELEPHONE,
	T_USER.TELEPHONE_SHORT AS F_TELEPHONE_SHORT,
	T_USER.MOBILE_NO AS F_MOBILE_NO,
	T_USER.MOBILE_NO_SHORT AS F_MOBILE_NO_SHORT,
	T_USER.CRT_TIME AS F_CRT_TIME,
	T_USER.CRT_USER AS F_CRT_USER,
	T_USER.ORG_ID AS F_DEPT_ID,
	TRIM (T_USER.IS_NEW_USER) AS F_IS_NEW_USER,
	T_USER.DATA_UPD_TIME AS F_DATA_UPD_TIME,
	T_USER.DATA_UPD_USER AS F_DATA_UPD_USER,
	T_USER.DATA_VALID_FLAG AS F_DATA_VALID_FLAG,
	T_USER.LOGIN_STATUS AS F_LOGIN_STATUS,
	T_USER.LOGOUT_TYPE AS F_LOGOUT_TYPE,
	T_USER.DEPT_CODE AS F_DEPT_CODE,
	T_USER.POSITION_CODE AS F_POSITION_CODE,
	T_USER.CURRENT_ORGID AS F_CURRENT_ORGID,
	T_USER.ADMIN_FLAG AS F_ADMIN_FLAG,
	T_USER.STAFF_NO AS F_STAFF_NO,
	T_USER.NATION AS F_NATION,
	T_USER.NATIVE_PLACE AS F_NATIVE_PLACE,
	T_USER.APPARAT AS F_APPARAT,
	T_USER.BIRTHDAY AS F_BIRTHDAY,
	T_USER.EDUCATION AS F_EDUCATION,
	T_USER.FINISH_TIME AS F_FINISH_TIME,
	T_USER.FINISH_SCHOOL AS F_FINISH_SCHOOL,
	T_USER.SPECIALTY AS F_SPECIALTY,
	T_USER.USER_TYPE AS F_USER_TYPE
FROM
	ZJPORTAL.T_USER@sso T_USER
LEFT JOIN ZJPORTAL.HR_SSO_USERINF@sso USERINFO ON T_USER.USER_ID = USERINFO.USER_ID
WHERE
	T_USER.CURRENT_ORGID = '3201';
-----------------------------------------------------------------------------------
--更新系统中没有的人员
INSERT INTO T_PUB_USER (
	F_USER_ID,
	F_LOGIN_NAME,
	F_LOGIN_PWD,
	F_FIRST_NAME,
	F_MIDDLE_NAME,
	F_DISPLAY_NAME,
	F_SEX,
	F_EMAIL,
	F_ID_CARD_NO,
	F_TELEPHONE,
	F_TELEPHONE_SHORT,
	F_MOBILE_NO,
	F_MOBILE_NO_SHORT,
	F_CRT_TIME,
	F_CRT_USER,
	F_DEPT_ID,
	F_IS_NEW_USER,
	F_DATA_UPD_TIME,
	F_DATA_UPD_USER,
	F_DATA_VALID_FLAG,
	F_LOGIN_STATUS,
	F_LOGOUT_TYPE,
	F_DEPT_CODE,
	F_POSITION_CODE,
	F_CURRENT_ORGID,
	F_ADMIN_FLAG,
	F_STAFF_NO,
	F_NATION,
	F_NATIVE_PLACE,
	F_APPARAT,
	F_BIRTHDAY,
	F_EDUCATION,
	F_FINISH_TIME,
	F_FINISH_SCHOOL,
	F_SPECIALTY,
	F_USER_TYPE
) SELECT
	T_USER.USER_ID AS F_USER_ID,
	SUBSTR (
		T_USER.LOGIN_NAME,
		0,
		(
			INSTR (
				T_USER.LOGIN_NAME,
				'@jsciq',
				1,
				1
			) - 1
		)
	) AS F_LOGIN_NAME,
	USERINFO.LOGIN_PWD AS F_LOGIN_PWD,
	T_USER.FIRST_NAME AS F_FIRST_NAME,
	T_USER.MIDDLE_NAME AS F_MIDDLE_NAME,
	T_USER.DISPLAY_NAME AS F_DISPLAY_NAME,
	TRIM (T_USER.SEX) AS F_SEX,
	T_USER.EMAIL AS F_EMAIL,
	T_USER.ID_CARD_NO AS F_ID_CARD_NO,
	T_USER.TELEPHONE AS F_TELEPHONE,
	T_USER.TELEPHONE_SHORT AS F_TELEPHONE_SHORT,
	T_USER.MOBILE_NO AS F_MOBILE_NO,
	T_USER.MOBILE_NO_SHORT AS F_MOBILE_NO_SHORT,
	T_USER.CRT_TIME AS F_CRT_TIME,
	T_USER.CRT_USER AS F_CRT_USER,
	T_USER.ORG_ID AS F_DEPT_ID,
	TRIM (T_USER.IS_NEW_USER) AS F_IS_NEW_USER,
	T_USER.DATA_UPD_TIME AS F_DATA_UPD_TIME,
	T_USER.DATA_UPD_USER AS F_DATA_UPD_USER,
	T_USER.DATA_VALID_FLAG AS F_DATA_VALID_FLAG,
	T_USER.LOGIN_STATUS AS F_LOGIN_STATUS,
	T_USER.LOGOUT_TYPE AS F_LOGOUT_TYPE,
	T_USER.DEPT_CODE AS F_DEPT_CODE,
	T_USER.POSITION_CODE AS F_POSITION_CODE,
	T_USER.CURRENT_ORGID AS F_CURRENT_ORGID,
	T_USER.ADMIN_FLAG AS F_ADMIN_FLAG,
	T_USER.STAFF_NO AS F_STAFF_NO,
	T_USER.NATION AS F_NATION,
	T_USER.NATIVE_PLACE AS F_NATIVE_PLACE,
	T_USER.APPARAT AS F_APPARAT,
	T_USER.BIRTHDAY AS F_BIRTHDAY,
	T_USER.EDUCATION AS F_EDUCATION,
	T_USER.FINISH_TIME AS F_FINISH_TIME,
	T_USER.FINISH_SCHOOL AS F_FINISH_SCHOOL,
	T_USER.SPECIALTY AS F_SPECIALTY,
	T_USER.USER_TYPE AS F_USER_TYPE

FROM
	ZJPORTAL.T_USER@sso T_USER
LEFT JOIN ZJPORTAL.HR_SSO_USERINF@sso USERINFO ON T_USER.USER_ID = USERINFO.USER_ID
WHERE
	T_USER.CURRENT_ORGID = '3201'
and not EXISTS (
	SELECT 1 FROM T_PUB_USER T1 WHERE SUBSTR(T_USER.LOGIN_NAME,0,(INSTR(T_USER.LOGIN_NAME,'@jsciq', 1, 1)-1))=T1.F_LOGIN_NAME
);