INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AE','阿联酋(UNITED EMIRATES)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AF','阿富汗(AFGHANISTAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AL','阿尔巴尼亚(ALBANIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AM','亚美尼亚(ARMENIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AO','安哥拉(ANGOLA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AR','阿根廷(ARGENTINA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AT','奥地利(AUSTRIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AU','澳大利亚(AUSTRALIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('AZ','阿塞拜疆(AZERBAIJAN(REPUBLIC))');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BD','孟加拉(BANGLADESH)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BE','比利时(BELGIUM)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BF','布基纳法索(BURKINA FASO)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BG','保加利亚(BULGARIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BH','巴林(BAHREIN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BI','布隆迪(BURUNDI)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BJ','贝宁(BENIN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BL','巴勒斯坦(STATE OF PALESTINE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BN','文莱(BRUNEI DARUSSALAM)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BO','玻利维亚(BOLIVIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BR','巴西(BRAZIL)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BW','博茨瓦纳(BOTSWANA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('BY','白俄罗斯(BYELORUSSIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CA','加拿大(CANADA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CF','中非(CENTRAL AFRICA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CG','刚果(CONGO)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CH','瑞士(SWITZERLAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CL','智利(CHILE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CM','喀麦隆(CAMEROON)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CN','中囯(CHINA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CO','哥伦比亚(COLOMBIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CR','哥斯达黎加(COSTA RICA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CS','捷克(CZECH REPUBIC)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CU','古巴(CUBA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('CY','塞浦路斯(CYPRUS)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('DE','德国(GERMANY)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('DK','丹麦(DENMARK)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('DO','多米尼加共和国(DOMINICAN REPUBLIC)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('DZ','阿尔及利亚(ALGERIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('EC','厄瓜多尔(ECUADOR)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('EE','爱沙尼亚(ESTONIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('EG','埃及(EGYPT)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ES','西班牙(SPAIN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ET','埃塞俄比亚(ETHIOPIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('FI','芬兰(FINLAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('FJ','斐济(FIJI)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('FR','法国(FRANCE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GA','加蓬(GABON)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GB','英国(UNITED KINGDOM)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GD','格林纳达(GRENADA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GE','格鲁吉亚(GEORGIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GH','加纳(GHANA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GN','几内亚(GUINEA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GR','希腊(GREECE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('GT','危地马拉(GUATEMALA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('HK','香港特别行政区(HONG KONG)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('HN','洪都拉斯(HONDURAS)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('HU','匈牙利(HUNGARY)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ID','印度尼西亚(INDONESIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('IE','爱尔兰(IRELAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('IL','以色列(ISRAEL)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('IN','印度(INDIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('IQ','伊拉克(IRAQ)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('IR','伊朗(IRAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('IS','冰岛(ICELAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('IT','意大利(ITALY)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('JM','牙买加(JAMAICA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('JO','约旦(JORDAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('JP','日本(JAPAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('KG','吉尔吉斯坦(KYRGYZSTAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('KH','柬埔寨(KAMPUCHEA(CAMBODIA))');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('KP','北朝鲜(KOREA,DEM.PEOPLE''S)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('KR','韩国(REPUBLIC OF KOREA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('KT','科特迪瓦共和国(COTE O''IVOIRE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('KW','科威特(KUWATI)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('KZ','哈萨克(KAZAKHSTAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LA','老挝(LAOS)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LB','黎巴嫩(LEBANON)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LC','圣卢西亚(SAINT LUEIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LI','列支敦士登(LIECHTENSTEIN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LK','斯里兰卡(SRI LANKA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LR','利比里亚(LIBERIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LT','立陶宛(LITHUANIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LU','卢森堡(LUXEMBOURG)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LV','拉脱维亚(LATVIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('LY','利比亚(LIBYAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MA','摩洛哥(MOROCCO)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MC','摩纳哥(MONACO)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MD','摩尔多瓦(MOLDOVA,REPUBLIC OF)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MG','马达加斯加(MADAGASCAR)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ML','马里(MALI)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MM','缅甸(BURMA(MYANMAR))');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MN','蒙古(MONGOLIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MO','澳门地区(MACAU)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MT','马耳他(MALTA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MU','毛里求斯(MAURITIUS)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MW','马拉维(MALAWI)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MX','墨西哥(MEXICO)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MY','马来西亚(MALAYSIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('MZ','莫桑比克(MOZAMBIQUE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NA','纳米比亚(NAMIBIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NE','尼日尔(NIGER)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NG','尼日利亚(NIGERIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NI','尼加拉瓜(NICARAGUA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NL','荷兰(NETHERLANDS)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NO','挪威(NORWAY)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NP','尼泊尔(NEPAL)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('NZ','新西兰(NEW ZEALAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('OM','阿曼(OMAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PA','巴拿马(PANAMA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PE','秘鲁(PERU)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PG','巴布亚新几内亚(PAPUA NEW GUINEA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PH','菲律宾(PHILIPPINES)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PK','巴基斯坦(PAKISTAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PL','波兰(POLAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PT','葡萄牙(PORTUGAL)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('PY','巴拉圭(PARAGUAY)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('QA','卡塔尔(QATAR)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('RRO','罗马尼亚(ROMANIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('RU','俄罗斯(RUSSIAN FEDERATION)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SA','沙特阿拉伯(SAUDI ARABIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SC','塞舌尔(SEYCHELLES)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SD','苏丹(SUDAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SE','瑞典(SWEDEN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SG','新加坡(SINGAPORE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SI','斯洛文尼亚(SLOVENIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SK','斯洛伐克(SLOVAKIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SM','圣马力诺(SAN MARINO)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SN','塞内加尔(SENEGAL)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SO','索马里(SOMALIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SY','叙利亚(SYRIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('SZ','斯威士兰(SWAZILAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TD','乍得(CHAD)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TG','多哥(TOGO)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TH','泰国(THAILAND)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TJ','塔吉克斯坦(TAJIKISTAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TM','土库曼(TURKMENISTAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TN','突尼斯(TUNISIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TR','土耳其(TURKEY)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TW','台湾省(TAIWAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('TZ','坦桑尼亚(TANZANIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('UA','乌克兰(UKRAINE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('UG','乌干达(UGANDA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('US','美国(UNITED STATES)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('UY','乌拉圭(URUGUAY)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('UZ','乌兹别克(UZBEKISTAN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('VC','圣文森特岛(SAINT VINCENT)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('VE','委内瑞拉(VENEZUELA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('VN','越南(VIET NAM)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('YE','也门(YEMEN)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('YU','南斯拉夫联盟(YUGOSLAVIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ZA','南非(SOUTH AFRICA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ZM','赞比亚(ZAMBIA)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ZR','扎伊尔(ZAIRE)');
INSERT INTO T_POST_NATION (F_NATION_NO, F_NATION_NAME) VALUES ('ZW','津巴布韦(ZIMBABWE)');


---------------2014-08-19--------------------
-----添加字段 国家（英文）
alter table T_POST_NATION
add F_NATION_NAME_EN VARCHAR2(150);

-----添加备注
COMMENT ON COLUMN "APMP"."T_POST_NATION"."F_NATION_NAME_EN" IS '国家名称(英文)';

-----更新国家（英文）
update T_POST_NATION a
set F_NATION_NAME_EN=(select SUBSTR(b.F_NATION_NAME, instr(b.F_NATION_NAME, '(')+1, length(b.F_NATION_NAME)-instr(b.F_NATION_NAME, '(')-1) AS EN from T_POST_NATION b WHERE a.F_NATION_NO = b.F_NATION_NO)
where exists (select 1
from T_POST_NATION b
where a.F_NATION_NO = b.F_NATION_NO
);

-----更新国家（中文）
update T_POST_NATION a
set F_NATION_NAME=(select SUBSTR(b.F_NATION_NAME, 0, instr(b.F_NATION_NAME, '(')-1) AS CN from T_POST_NATION b WHERE a.F_NATION_NO = b.F_NATION_NO)
where exists (select 1
from T_POST_NATION b
where a.F_NATION_NO = b.F_NATION_NO
);
---------------2014-08-19--------------------